# Generated by Django 4.1.7 on 2023-08-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PocketServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_fio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО'),
        ),
    ]
