# Generated by Django 4.1.7 on 2023-08-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PocketServiceApp', '0004_agent_products_alter_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='object_information',
        ),
    ]
