# Generated by Django 4.1.7 on 2023-08-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PocketServiceApp', '0005_remove_client_object_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_flag',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Не в работе'), (1, 'В работе'), (2, 'Приостановлена'), (3, 'Выполнена')], default=0, null=True, verbose_name='Статус выполнения'),
        ),
    ]
