# Generated by Django 4.1.7 on 2023-08-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PocketServiceApp', '0006_order_status_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок конца работы'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок начала работы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запланированный срок конца работы'),
        ),
    ]
