# Generated by Django 4.1.7 on 2023-09-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PocketServiceApp', '0008_remove_person_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Ремонт квартиры'), (1, 'Ремонт техники'), (2, 'Ремонт мебели'), (3, 'Услуги красоты'), (4, 'Уборка')], null=True, verbose_name='Тип услуги'),
        ),
    ]
