# Generated by Django 4.1.7 on 2023-09-20 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PocketServiceApp', '0009_alter_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('flag', models.BooleanField(default=1, verbose_name='Флаг активности')),
                ('price_value', models.CharField(blank=True, max_length=30, null=True, verbose_name='Цена')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_price', to='PocketServiceApp.product', verbose_name='Услуга')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['creation_datetime'], name='index_price_time'),
        ),
    ]
