# Generated by Django 4.1.7 on 2023-09-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PocketServiceApp', '0011_price_agent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='price',
            name='index_price_time',
        ),
        migrations.AlterModelTable(
            name='price',
            table='price',
        ),
    ]
