# Generated by Django 4.1.7 on 2023-09-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PocketServiceApp', '0012_remove_price_index_price_time_alter_price_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('flag', models.BooleanField(default=1, verbose_name='Флаг активности')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название специализации')),
                ('specialization_description', models.TextField(blank=True, null=True, verbose_name='Описание специализации')),
            ],
            options={
                'db_table': 'specialization',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('flag', models.BooleanField(default=1, verbose_name='Флаг активности')),
                ('name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Название института/колледжа/школы')),
                ('university_description', models.TextField(blank=True, null=True, verbose_name='Описание места учебы')),
            ],
            options={
                'db_table': 'university',
            },
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата конца работ'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала работ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Запланированный срок конца работы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateField(blank=True, null=True, verbose_name='Срок конца работы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateField(blank=True, null=True, verbose_name='Срок начала работы'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('flag', models.BooleanField(default=1, verbose_name='Флаг активности')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Срок начала учебы')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Срок конца учебы')),
                ('document_check', models.BooleanField(blank=True, null=True, verbose_name='Проверка документа')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_education', to='PocketServiceApp.agent', verbose_name='Агент')),
                ('specialization', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='specialization', to='PocketServiceApp.specialization', verbose_name='Специальность')),
                ('university', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='university', to='PocketServiceApp.university', verbose_name='Место учебы')),
            ],
            options={
                'db_table': 'education',
            },
        ),
    ]
