# Generated by Django 4.1.7 on 2023-09-29 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PocketServiceApp', '0013_specialization_university_alter_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialization', to='PocketServiceApp.specialization', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university', to='PocketServiceApp.university', verbose_name='Место учебы'),
        ),
    ]
