# Generated by Django 4.1.7 on 2023-10-05 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PocketServiceApp', '0014_alter_education_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education', to='PocketServiceApp.agent', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='education',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education', to='PocketServiceApp.specialization', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education', to='PocketServiceApp.university', verbose_name='Место учебы'),
        ),
    ]
