# Generated by Django 4.1.7 on 2023-10-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PocketServiceApp', '0016_comment_commentimages_personfiles_personimages_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentimages',
            table='comment_image',
        ),
        migrations.AlterModelTable(
            name='personfiles',
            table='person_file',
        ),
        migrations.AlterModelTable(
            name='personimages',
            table='person_image',
        ),
    ]
