# Generated by Django 4.1.7 on 2023-11-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PocketServiceApp', '0018_remove_agent_education_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='town',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Город'),
        ),
    ]
