version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    # '/start' is the shell script used to run the service
    command: /start
    ports:
      - 8000:8000
    volumes:
      - .:/PocketServiceProject
    env_file:
      - ./.env/.env.dev
    depends_on:
      - redis
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=PocketServiceDB
    ports:
      - 5433:5432

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start-celeryworker
    volumes:
      - .:/PocketServiceProject
    env_file:
      - ./.env/.env.dev
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start-celerybeat
    volumes:
      - .:/PocketServiceProject
    env_file:
      - ./.env/.env.dev
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start-flower
    volumes:
      - .:/PocketServiceProject
    env_file:
      - ./.env/.env.dev
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

  telegrambot:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: telegrambot
    command: /entrybot
    volumes:
      - .:/PocketServiceProject
    env_file:
      - ./.env/.env.dev
    depends_on:
      - redis
      - db
      - app

  pgadmin:
    container_name: pgadmin_container_for_hcs
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "123@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  postgres_data: