# Generated by Django 4.1.7 on 2023-03-16 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('flag', models.BooleanField(default=1, verbose_name='Флаг активности')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта')),
                ('total_amount', models.CharField(blank=True, max_length=255, null=True, verbose_name='Итоговая сумма')),
                ('invoice_payload', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice payload')),
                ('provider_payment_charge_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Provider Payment Charge ID')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('status_str', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status Str')),
                ('operation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Operation')),
                ('masked_pan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Masked Pan')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name')),
                ('payment_way', models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Way')),
                ('expiry', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expiry')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Time')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='OnlinePayment',
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['area_name'], name='index_area_name'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['name'], name='index_name_order'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['phone_number'], name='index_persons_phone_number'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['telegram_id'], name='index_persons_telegram_id'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['email'], name='index_persons_email'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='index_name_product'),
        ),
        migrations.AlterModelTable(
            name='administrator',
            table='administrators',
        ),
        migrations.AlterModelTable(
            name='agent',
            table='agents',
        ),
        migrations.AlterModelTable(
            name='area',
            table='areas',
        ),
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='fileobject',
            table='file_objects',
        ),
        migrations.AlterModelTable(
            name='imageobject',
            table='image_objects',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='person',
            table='persons',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.AddField(
            model_name='onlinetransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='hr_system.order', verbose_name='Заказ'),
        ),
    ]
