# Generated by Django 4.1.7 on 2023-03-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0002_onlinetransaction_delete_onlinepayment_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['creation_datetime'], name='role_creation_datetime_index'),
        ),
        migrations.AlterModelTable(
            name='onlinetransaction',
            table='Transactions',
        ),
    ]
