# Generated by Django 4.1.7 on 2023-03-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0003_role_role_creation_datetime_index_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='role',
            new_name='index_role_time',
            old_name='role_creation_datetime_index',
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['creation_datetime'], name='index_area_time'),
        ),
        migrations.AddIndex(
            model_name='fileobject',
            index=models.Index(fields=['creation_datetime'], name='index_fileobject_time'),
        ),
        migrations.AddIndex(
            model_name='imageobject',
            index=models.Index(fields=['creation_datetime'], name='index_imageobject_time'),
        ),
        migrations.AddIndex(
            model_name='onlinetransaction',
            index=models.Index(fields=['creation_datetime'], name='index_onlinetransaction_time'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['creation_datetime'], name='index_order_time'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['creation_datetime'], name='index_person_time'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['creation_datetime'], name='index_product_time'),
        ),
        migrations.AlterModelTable(
            name='area',
            table='area',
        ),
        migrations.AlterModelTable(
            name='fileobject',
            table='file_object',
        ),
        migrations.AlterModelTable(
            name='imageobject',
            table='image_object',
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
    ]
