# Generated by Django 4.1.7 on 2023-03-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0004_rename_role_creation_datetime_index_index_role_time_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administrator',
            table='administrator',
        ),
        migrations.AlterModelTable(
            name='agent',
            table='agent',
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
