# Generated by Django 4.1.7 on 2023-03-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0006_alter_person_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='area',
        ),
        migrations.AddField(
            model_name='agent',
            name='area',
            field=models.ManyToManyField(blank=True, null=True, related_name='area_agents', to='hr_system.area', verbose_name='Районы'),
        ),
    ]
