# Generated by Django 4.1.7 on 2023-03-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0007_remove_agent_area_agent_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='area',
            field=models.ManyToManyField(blank=True, related_name='area_agents', to='hr_system.area', verbose_name='Районы'),
        ),
        migrations.AlterField(
            model_name='fileobject',
            name='person_file',
            field=models.FileField(blank=True, null=True, upload_to='./postgres_data/objects/persons/files/', verbose_name='Файл пользователя'),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='person_image',
            field=models.ImageField(blank=True, null=True, upload_to='./postgres_data/objects/persons/images/', verbose_name='Картинка пользователя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='./postgres_data/objects/persons/background/', verbose_name='Аватар пользователя '),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='./postgres_data/objects/products/images/', verbose_name='Картинка услуг'),
        ),
    ]
