# Generated by Django 4.1.7 on 2023-05-25 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0008_alter_agent_area_alter_fileobject_person_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('flag', models.BooleanField(default=1, verbose_name='Флаг активности')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название контракта')),
                ('number_contract', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер договора')),
                ('begin_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата конца')),
            ],
            options={
                'db_table': 'сontract',
            },
        ),
        migrations.CreateModel(
            name='Smeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('flag', models.BooleanField(default=1, verbose_name='Флаг активности')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название сметы')),
                ('smeta_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Смета на работы'), (1, 'Смета на материалы')], null=True, verbose_name='Тип сметы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание сметы')),
                ('name_work', models.CharField(blank=True, max_length=20, null=True, verbose_name='Наименование работ/материалов')),
                ('quantity', models.CharField(blank=True, max_length=20, null=True, verbose_name='Кол-во')),
                ('unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='Единица измерения')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_smeta', to='hr_system.contract', verbose_name='Контракт')),
            ],
            options={
                'db_table': 'smeta',
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['creation_datetime'], name='index_contract_time'),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_image', to='hr_system.contract', verbose_name='Контракт'),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='smeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smeta_image', to='hr_system.smeta', verbose_name='Смета'),
        ),
        migrations.AddIndex(
            model_name='smeta',
            index=models.Index(fields=['creation_datetime'], name='index_smeta_time'),
        ),
    ]
