# Generated by Django 4.1.7 on 2023-05-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0009_contract_smeta_contract_index_contract_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Чата'),
        ),
        migrations.AddField(
            model_name='person',
            name='telegram_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя пользователя Телеграмм'),
        ),
        migrations.AddField(
            model_name='person',
            name='telegram_surname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия пользователя Телеграмм'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Пользователь Телеграмм'),
        ),
    ]
