# Generated by Django 4.1.7 on 2023-05-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0010_person_telegram_chat_id_person_telegram_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileobject',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='fileobject',
            name='person',
        ),
        migrations.RemoveField(
            model_name='fileobject',
            name='smeta',
        ),
        migrations.RemoveField(
            model_name='imageobject',
            name='person',
        ),
        migrations.RemoveField(
            model_name='smeta',
            name='contract',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='FileObject',
        ),
        migrations.DeleteModel(
            name='ImageObject',
        ),
        migrations.DeleteModel(
            name='Smeta',
        ),
    ]
