# Generated by Django 4.1.7 on 2023-05-29 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0011_remove_fileobject_contract_remove_fileobject_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('flag', models.BooleanField(default=1, verbose_name='Флаг активности')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название контракта')),
                ('contract_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер договора')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала работ')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата конца работ')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_order', to='hr_system.order', verbose_name='Заявка')),
            ],
            options={
                'db_table': 'сontract',
            },
        ),
        migrations.CreateModel(
            name='Smeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('flag', models.BooleanField(default=1, verbose_name='Флаг активности')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название сметы')),
                ('smeta_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Смета на работы'), (1, 'Смета на материалы')], null=True, verbose_name='Тип сметы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание сметы')),
                ('name_work', models.CharField(blank=True, max_length=20, null=True, verbose_name='Наименование работ/материалов')),
                ('quantity', models.CharField(blank=True, max_length=20, null=True, verbose_name='Кол-во')),
                ('unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='Единица измерения')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_smeta', to='hr_system.contract', verbose_name='Контракт')),
            ],
            options={
                'db_table': 'smeta',
            },
        ),
        migrations.CreateModel(
            name='ImageObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('flag', models.BooleanField(default=1, verbose_name='Флаг активности')),
                ('image_object', models.ImageField(blank=True, null=True, upload_to='./postgres_data/objects/persons/images/', verbose_name='Объект картинки')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_image', to='hr_system.contract', verbose_name='Картинки для контракта')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_image', to='hr_system.person', verbose_name='Картинки пользователя')),
                ('smeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smeta_image', to='hr_system.smeta', verbose_name='Картинки для сметы')),
            ],
            options={
                'db_table': 'image_object',
            },
        ),
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('flag', models.BooleanField(default=1, verbose_name='Флаг активности')),
                ('object_type', models.CharField(max_length=100, verbose_name='Тип объекта')),
                ('file_object', models.FileField(blank=True, null=True, upload_to='./postgres_data/objects/persons/files/', verbose_name='Объект файла')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_file', to='hr_system.contract', verbose_name='Файлы для контракта')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_files', to='hr_system.person', verbose_name='Файлы пользователя')),
                ('smeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smeta_file', to='hr_system.smeta', verbose_name='Файлы для сметы')),
            ],
            options={
                'db_table': 'file_object',
            },
        ),
        migrations.AddIndex(
            model_name='smeta',
            index=models.Index(fields=['creation_datetime'], name='index_smeta_time'),
        ),
        migrations.AddIndex(
            model_name='imageobject',
            index=models.Index(fields=['creation_datetime'], name='index_imageobject_time'),
        ),
        migrations.AddIndex(
            model_name='fileobject',
            index=models.Index(fields=['creation_datetime'], name='index_fileobject_time'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['creation_datetime'], name='index_contract_time'),
        ),
    ]
