# Generated by Django 4.1.7 on 2023-05-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0012_contract_smeta_imageobject_fileobject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileobject',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='fileobject',
            name='person',
        ),
        migrations.RemoveField(
            model_name='fileobject',
            name='smeta',
        ),
        migrations.RemoveField(
            model_name='imageobject',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='imageobject',
            name='person',
        ),
        migrations.RemoveField(
            model_name='imageobject',
            name='smeta',
        ),
        migrations.RemoveField(
            model_name='onlinetransaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='order',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='smeta',
            name='contract',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='FileObject',
        ),
        migrations.DeleteModel(
            name='ImageObject',
        ),
        migrations.DeleteModel(
            name='OnlineTransaction',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Smeta',
        ),
    ]
