# Generated by Django 4.1.7 on 2023-05-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0014_contract_fileobject_imageobject_onlinetransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Ремонт квартиры'), (1, 'Ремонт сантехники'), (2, 'Ремонт мебели'), (3, 'Уборка')], null=True, verbose_name='Тип услуги'),
        ),
    ]
