#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic --noinput
python manage.py init_admin

/usr/local/bin/gunicorn PocketServiceApp.asgi:application --bind 0.0.0.0:8000 --chdir=/PocketServiceApp